feat: add component card and section of courses
waelelsafty07/waell-bld.ai-project2 pull request #1
Opened 2022-08-23 09:52 UTC by waelelsafty07

2022-08-24 19:53 UTC, shereen-fathy requested changes
small changes just to match task requirements

2022-08-24 19:53 UTC, shereen-fathy commented on src/components/CardDetails/CardDetails.js
> +const CardDetails = ({ image, title, author, rating, price, people }) => {
`CouseCard or CourseDetails` will be a more appropriate name here

2022-08-24 19:53 UTC, shereen-fathy commented on src/components/Courses/Courses.js
> +        <h2>Expand your career opportunities with Python</h2>
according to the requirements, you should take courses, title, and description as a prop to this component, right?

2022-08-26 04:38 UTC, waelelsafty07 commented on src/components/Courses/Courses.js
> +        <h2>Expand your career opportunities with Python</h2>
I, didn't know about that, i will fix that

2022-08-26 04:42 UTC, waelelsafty07 commented on src/components/Courses/Courses.js
> +        <h2>Expand your career opportunities with Python</h2>
Sorry for forgetting that

2022-08-29 10:22 UTC, shereen-fathy approved these changes
Thank you for the changes

2022-08-31 10:58 UTC, merged